services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: servp
      POSTGRES_PASSWORD: servp
      POSTGRES_DB: servp
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U servp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app/server
    command: sh -c "cd server && ./scripts/init_db.sh"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ./server:/app/server
