services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: servp
      POSTGRES_PASSWORD: servp
      POSTGRES_DB: servp
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U servp"]
      interval: 10s
      timeout: 5s
      retries: 5


  db-init:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app/server
    command: sh -c "/app/server/scripts/init_db.sh"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - UPLOAD_DIR=/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      db-init:
        condition: service_completed_successfully
    volumes:
      - ./server:/app/server
      - ./uploads:/app/uploads

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
