"""add user table

Revision ID: b43e2280f258
Revises: 85c47b9993e8
Create Date: 2026-03-18 02:27:57.522523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b43e2280f258'
down_revision: Union[str, Sequence[str], None] = '85c47b9993e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('users', sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('users', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('users', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('users', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.alter_column('users', 'openid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'status')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('REPORTER', 'ENGINEER', 'DISPATCHER', 'LEADER', 'ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.alter_column('users', 'openid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'phone')
    op.drop_column('users', 'language')
    op.drop_column('users', 'country')
    op.drop_column('users', 'province')
    op.drop_column('users', 'city')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
